// Preloaded 100 Hindi-English flashcards
const preloadedFlashcards = [
  { id: 1, front: 'नमस्ते', back: 'Hello',  },
  { id: 2, front: 'धन्यवाद', back: 'Thank you',  },
  { id: 3, front: 'हाँ', back: 'Yes',  },
  { id: 4, front: 'नहीं', back: 'No',  },
  { id: 5, front: 'मैं', back: 'I',  },
  { id: 6, front: 'तुम', back: 'You',  },
  { id: 7, front: 'हम', back: 'We',  },
  { id: 8, front: 'वे', back: 'They',  },
  { id: 9, front: 'खाना', back: 'Food',  },
  { id: 10, front: 'पानी', back: 'Water',  },
  { id: 11, front: 'अच्छा', back: 'Good',  },
  { id: 12, front: 'बुरा', back: 'Bad',  },
  { id: 13, front: 'प्यार', back: 'Love',  },
  { id: 14, front: 'दोस्त', back: 'Friend',  },
  { id: 15, front: 'परिवार', back: 'Family',  },
  { id: 16, front: 'घर', back: 'Home',  },
  { id: 17, front: 'समय', back: 'Time',  },
  { id: 18, front: 'दिन', back: 'Day',  },
  { id: 19, front: 'रात', back: 'Night',  },
  { id: 20, front: 'आज', back: 'Today',  },
  { id: 21, front: 'कल', back: 'Tomorrow',  },
  { id: 22, front: 'बीता हुआ कल', back: 'Yesterday',  },
  { id: 23, front: 'भारत', back: 'India',  },
  { id: 24, front: 'भाषा', back: 'Language',  },
  { id: 25, front: 'स्कूल', back: 'School',  },
  { id: 26, front: 'किताब', back: 'Book',  },
  { id: 27, front: 'पेन', back: 'Pen',  },
  { id: 28, front: 'सवाल', back: 'Question',  },
  { id: 29, front: 'जवाब', back: 'Answer',  },
  { id: 30, front: 'खेल', back: 'Game',  },
  { id: 31, front: 'संगीत', back: 'Music',  },
  { id: 32, front: 'फिल्म', back: 'Movie',  },
  { id: 33, front: 'नाच', back: 'Dance',  },
  { id: 34, front: 'आकाश', back: 'Sky',  },
  { id: 35, front: 'तारे', back: 'Stars',  },
  { id: 36, front: 'धरती', back: 'Earth',  },
  { id: 37, front: 'सूरज', back: 'Sun',  },
  { id: 38, front: 'चाँद', back: 'Moon',  },
  { id: 39, front: 'पेड़', back: 'Tree',  },
  { id: 40, front: 'फूल', back: 'Flower',  },
  { id: 41, front: 'जानवर', back: 'Animal',  },
  { id: 42, front: 'कुत्ता', back: 'Dog',  },
  { id: 43, front: 'बिल्ली', back: 'Cat',  },
  { id: 44, front: 'हाथी', back: 'Elephant',  },
  { id: 45, front: 'चिड़िया', back: 'Bird',  },
  { id: 46, front: 'मछली', back: 'Fish',  },
  { id: 47, front: 'साँप', back: 'Snake',  },
  { id: 48, front: 'शेर', back: 'Lion',  },
  { id: 49, front: 'हवा', back: 'Air',  },
  { id: 50, front: 'आग', back: 'Fire',  },
  { id: 51, front: 'रंग', back: 'Color',  },
  { id: 52, front: 'लाल', back: 'Red',  },
  { id: 53, front: 'नीला', back: 'Blue',  },
  { id: 54, front: 'हरा', back: 'Green',  },
  { id: 55, front: 'पीला', back: 'Yellow',  },
  { id: 56, front: 'काला', back: 'Black',  },
  { id: 57, front: 'सफेद', back: 'White',  },
  { id: 58, front: 'बड़ा', back: 'Big',  },
  { id: 59, front: 'छोटा', back: 'Small',  },
  { id: 60, front: 'लंबा', back: 'Tall',  },
  { id: 61, front: 'नाटा', back: 'Short',  },
  { id: 62, front: 'मोटा', back: 'Fat',  },
  { id: 63, front: 'पतला', back: 'Thin',  },
  { id: 64, front: 'गरम', back: 'Hot',  },
  { id: 65, front: 'ठंडा', back: 'Cold',  },
  { id: 66, front: 'तेज', back: 'Fast',  },
  { id: 67, front: 'धीमा', back: 'Slow',  },
  { id: 68, front: 'नया', back: 'New',  },
  { id: 69, front: 'पुराना', back: 'Old',  },
  { id: 70, front: 'सुंदर', back: 'Beautiful',  },
  { id: 71, front: 'बदसूरत', back: 'Ugly',  },
  { id: 72, front: 'खाना', back: 'To eat',  },
  { id: 73, front: 'पीना', back: 'To drink',  },
  { id: 74, front: 'सोना', back: 'To sleep',  },
  { id: 75, front: 'जागना', back: 'To wake up',  },
  { id: 76, front: 'बोलना', back: 'To speak',  },
  { id: 77, front: 'सुनना', back: 'To listen',  },
  { id: 78, front: 'देखना', back: 'To see',  },
  { id: 79, front: 'चलना', back: 'To walk',  },
  { id: 80, front: 'दौड़ना', back: 'To run',  },
  { id: 81, front: 'लिखना', back: 'To write',  },
  { id: 82, front: 'पढ़ना', back: 'To read',  },
  { id: 83, front: 'हँसना', back: 'To laugh',  },
  { id: 84, front: 'रोना', back: 'To cry',  },
  { id: 85, front: 'ले जाना', back: 'To take',  },
  { id: 86, front: 'देना', back: 'To give',  },
  { id: 87, front: 'जाना', back: 'To go',  },
  { id: 88, front: 'आना', back: 'To come',  },
  { id: 89, front: 'बैठना', back: 'To sit',  },
  { id: 90, front: 'खड़ा होना', back: 'To stand',  },
  { id: 91, front: 'खेलना', back: 'To play',  },
  { id: 92, front: 'समझना', back: 'To understand',  },
  { id: 93, front: 'सीखना', back: 'To learn',  },
  { id: 94, front: 'पहनना', back: 'To wear',  },
  { id: 95, front: 'खरीदना', back: 'To buy',  },
  { id: 96, front: 'बेचना', back: 'To sell',  },
  { id: 97, front: 'मिलना', back: 'To meet',  },
  { id: 98, front: 'याद रखना', back: 'To remember',  },
];

export default preloadedFlashcards;
